### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [pavdmyt/simple-oh-my-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Also, I like the idea of putting the git status in the iTerm window title, I look forward to other themes implementing this as well :-)

**Comment by pavdmyt** [comment]
@unixorn actually there is a [screenshot](https://github.com/pavdmyt/simple-oh-my-zsh-theme/blob/master/static/theme_in_nutshell.png) and it is visible in [README](https://github.com/pavdmyt/simple-oh-my-zsh-theme/blob/master/README.md)

Thanks for your interest 😃

**Comment by unixorn** [comment]
Not sure how I managed to miss that - adding in https://github.com/unixorn/awesome-zsh-plugins/pull/749
